#
# esf.properties
#
# This files lists Studio SDK properties pertaining to the multiprotocol examples package.
#
# The version=8.0.0.0
# release branch, or it should be set to 0.0.0 otherwise. This is the
# version that Studio displays for the loaded package.
#

id=com.silabs.sdk.multiprotocol
version=8.0.0.0
label=Multiprotocol
description=Multiprotocol Sample Applications

prop.partCompatibility=.*host.* .*rm21.* .*efr32m[gr]2.* .*mgm2.* .*simg301.*

prop.file.templatesFile=../multiprotocol/multiprotocol_production_templates.xml ../multiprotocol/multiprotocol_internal_templates.xml ../multiprotocol/multiprotocol_experimental_templates.xml
prop.file.demosFile=multiprotocol_production_demos.xml
