'''AUTOGENERATED BY test_gen_wisun_FAN1v1_py_files() - do not modify!'''

from pyradioconfig.parts.ocelot.phys.phys_studio_wisun_fan_1_1_virtual import PhysStudioWisunFan1v1VirtualOcelot
from pyradioconfig.parts.sol.phys.phys_studio_wisun_fan_1_1 import WisunFan1v1ChannelParamsSol

class PhysStudioWisunFan1v1VirtualSol(PhysStudioWisunFan1v1VirtualOcelot):   

    pass