# This file provides metadata for the stack directory, as part of ESF.
id=com.silabs.stack.connect
label=Connect SDK
description=Connect Software Development Kit

version=4.1.3
prop.subLabel=Connect\\ 4.1.3

# General properties are prepended with "prop."
prop.file.templatesFile=connect_production_templates.xml connect_demos_only_templates.xml connect_internal_templates.xml connect_evaluation_templates.xml
prop.file.adapterPacks=../../platform/radio/efr32_multiphy_configurator
prop.file.docsFile=documentation/slConnect_docContent.xml
prop.file.demosFile=connect_production_demos.xml connect_experimental_demos.xml connect_evaluation_demos.xml connect_deprecated_demos.xml connect_internal_demos.xml connect_demos_only_demos.xml
#prop.file.modulesFile=modules.xml
prop.partCompatibility=.*efr32[bfmz]g2.* .*mgm2.* .*rm21.* .*fgm230s.* .*zgm2.* .*bgm220sc2[2-3]hna.*
prop.boardCompatibility=.*
