'''AUTOGENERATED BY test_gen_wisun_FAN1v1_py_files() - do not modify!'''

from pyradioconfig.parts.jumbo.phys.phys_studio_wisun_fan_1_1_virtual import PhysStudioWisunFan1v1VirtualJumbo
from pyradioconfig.parts.ocelot.phys.phys_studio_wisun_fan_1_1 import WisunFan1v1ChannelParamsOcelot

class PhysStudioWisunFan1v1VirtualOcelot(PhysStudioWisunFan1v1VirtualJumbo):   

    def PHY_WISUN_FAN_1v1_915MHz_Plan48_2FSK_1b_AZ_NZ_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('AZ_NZ', 0x12, 48, 200000, 915200000, 'Wi-SUN FAN, AZ_NZ 915-928 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan48_2FSK_2a_AZ_NZ_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('AZ_NZ', 0x13, 48, 200000, 915200000, 'Wi-SUN FAN, AZ_NZ 915-928 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan49_2FSK_3_AZ_NZ_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('AZ_NZ', 0x15, 49, 400000, 915400000, 'Wi-SUN FAN, AZ_NZ 915-928 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan49_2FSK_4a_AZ_NZ_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('AZ_NZ', 0x16, 49, 400000, 915400000, 'Wi-SUN FAN, AZ_NZ 915-928 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan49_2FSK_5_AZ_NZ_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('AZ_NZ', 0x18, 49, 400000, 915400000, 'Wi-SUN FAN, AZ_NZ 915-928 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan128_2FSK_1b_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x12, 128, 250000, 920625000, 'Wi-SUN FAN, CN 920-924 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan128_2FSK_2a_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x13, 128, 250000, 920625000, 'Wi-SUN FAN, CN 920-924 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan128_2FSK_3_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x15, 128, 250000, 920625000, 'Wi-SUN FAN, CN 920-924 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_779MHz_Plan144_2FSK_1b_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x12, 144, 200000, 779200000, 'Wi-SUN FAN, CN 779-787 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_779MHz_Plan144_2FSK_2a_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x13, 144, 200000, 779200000, 'Wi-SUN FAN, CN 779-787 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_779MHz_Plan145_2FSK_3_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x15, 145, 400000, 779400000, 'Wi-SUN FAN, CN 779-787 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_779MHz_Plan145_2FSK_4a_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x16, 145, 400000, 779400000, 'Wi-SUN FAN, CN 779-787 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_779MHz_Plan145_2FSK_5_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x18, 145, 400000, 779400000, 'Wi-SUN FAN, CN 779-787 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_470MHz_Plan160_2FSK_1b_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x12, 160, 200000, 470200000, 'Wi-SUN FAN, CN 470-510 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_470MHz_Plan160_2FSK_2a_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x13, 160, 200000, 470200000, 'Wi-SUN FAN, CN 470-510 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_470MHz_Plan160_2FSK_3_CN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('CN', 0x15, 160, 200000, 470200000, 'Wi-SUN FAN, CN 470-510 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_1b_HK_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('HK', 0x12, 64, 200000, 920200000, 'Wi-SUN FAN, HK 920-925 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_2a_HK_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('HK', 0x13, 64, 200000, 920200000, 'Wi-SUN FAN, HK 920-925 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_3_HK_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('HK', 0x15, 65, 400000, 920400000, 'Wi-SUN FAN, HK 920-925 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_4a_HK_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('HK', 0x16, 65, 400000, 920400000, 'Wi-SUN FAN, HK 920-925 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_5_HK_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('HK', 0x18, 65, 400000, 920400000, 'Wi-SUN FAN, HK 920-925 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_917MHz_Plan96_2FSK_1b_KR_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('KR', 0x12, 96, 200000, 917100000, 'Wi-SUN FAN, KR 917-923 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_917MHz_Plan96_2FSK_2a_KR_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('KR', 0x13, 96, 200000, 917100000, 'Wi-SUN FAN, KR 917-923 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_917MHz_Plan97_2FSK_3_KR_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('KR', 0x15, 97, 400000, 917300000, 'Wi-SUN FAN, KR 917-923 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_917MHz_Plan97_2FSK_4a_KR_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('KR', 0x16, 97, 400000, 917300000, 'Wi-SUN FAN, KR 917-923 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_917MHz_Plan97_2FSK_5_KR_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('KR', 0x18, 97, 400000, 917300000, 'Wi-SUN FAN, KR 917-923 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_902MHz_Plan1_2FSK_1b_MX_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MX', 0x12, 1, 200000, 902200000, 'Wi-SUN FAN, MX 902-928 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_902MHz_Plan1_2FSK_2a_MX_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MX', 0x13, 1, 200000, 902200000, 'Wi-SUN FAN, MX 902-928 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_902MHz_Plan2_2FSK_3_MX_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MX', 0x15, 2, 400000, 902400000, 'Wi-SUN FAN, MX 902-928 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_902MHz_Plan2_2FSK_4a_MX_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MX', 0x16, 2, 400000, 902400000, 'Wi-SUN FAN, MX 902-928 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_902MHz_Plan2_2FSK_5_MX_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MX', 0x18, 2, 400000, 902400000, 'Wi-SUN FAN, MX 902-928 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_919MHz_Plan80_2FSK_1b_MY_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MY', 0x12, 80, 200000, 919200000, 'Wi-SUN FAN, MY 919-923 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_919MHz_Plan80_2FSK_2a_MY_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MY', 0x13, 80, 200000, 919200000, 'Wi-SUN FAN, MY 919-923 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_919MHz_Plan81_2FSK_3_MY_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MY', 0x15, 81, 400000, 919400000, 'Wi-SUN FAN, MY 919-923 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_919MHz_Plan81_2FSK_4a_MY_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MY', 0x16, 81, 400000, 919400000, 'Wi-SUN FAN, MY 919-923 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_919MHz_Plan81_2FSK_5_MY_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('MY', 0x18, 81, 400000, 919400000, 'Wi-SUN FAN, MY 919-923 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan48_2FSK_1b_PH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('PH', 0x12, 48, 200000, 915200000, 'Wi-SUN FAN, PH 915-918 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan48_2FSK_2a_PH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('PH', 0x13, 48, 200000, 915200000, 'Wi-SUN FAN, PH 915-918 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan49_2FSK_3_PH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('PH', 0x15, 49, 400000, 915400000, 'Wi-SUN FAN, PH 915-918 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan49_2FSK_4a_PH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('PH', 0x16, 49, 400000, 915400000, 'Wi-SUN FAN, PH 915-918 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_915MHz_Plan49_2FSK_5_PH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('PH', 0x18, 49, 400000, 915400000, 'Wi-SUN FAN, PH 915-918 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_866MHz_Plan32_2FSK_1a_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x11, 32, 100000, 866100000, 'Wi-SUN FAN, SG 866-869 MHz, Mode1a (2FSK 50kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_866MHz_Plan33_2FSK_2a_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x13, 33, 200000, 866100000, 'Wi-SUN FAN, SG 866-869 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_866MHz_Plan33_2FSK_3_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x15, 33, 200000, 866100000, 'Wi-SUN FAN, SG 866-869 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_1b_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x12, 64, 200000, 920200000, 'Wi-SUN FAN, SG 920-925 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_2a_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x13, 64, 200000, 920200000, 'Wi-SUN FAN, SG 920-925 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_3_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x15, 65, 400000, 920400000, 'Wi-SUN FAN, SG 920-925 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_4a_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x16, 65, 400000, 920400000, 'Wi-SUN FAN, SG 920-925 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_5_SG_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('SG', 0x18, 65, 400000, 920400000, 'Wi-SUN FAN, SG 920-925 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_1b_TH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('TH', 0x12, 64, 200000, 920200000, 'Wi-SUN FAN, TH 920-925 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_2a_TH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('TH', 0x13, 64, 200000, 920200000, 'Wi-SUN FAN, TH 920-925 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_3_TH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('TH', 0x15, 65, 400000, 920400000, 'Wi-SUN FAN, TH 920-925 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_4a_TH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('TH', 0x16, 65, 400000, 920400000, 'Wi-SUN FAN, TH 920-925 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_5_TH_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('TH', 0x18, 65, 400000, 920400000, 'Wi-SUN FAN, TH 920-925 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_1b_VN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('VN', 0x12, 64, 200000, 920200000, 'Wi-SUN FAN, VN 920-925 MHz, Mode1b (2FSK 50kbps mi=1.0), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan64_2FSK_2a_VN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('VN', 0x13, 64, 200000, 920200000, 'Wi-SUN FAN, VN 920-925 MHz, Mode2a (2FSK 100kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_3_VN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('VN', 0x15, 65, 400000, 920400000, 'Wi-SUN FAN, VN 920-925 MHz, Mode3 (2FSK 150kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_4a_VN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('VN', 0x16, 65, 400000, 920400000, 'Wi-SUN FAN, VN 920-925 MHz, Mode4a (2FSK 200kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    def PHY_WISUN_FAN_1v1_920MHz_Plan65_2FSK_5_VN_FEC(self, model, phy_name=None):
        params = WisunFan1v1ChannelParamsOcelot('VN', 0x18, 65, 400000, 920400000, 'Wi-SUN FAN, VN 920-925 MHz, Mode5 (2FSK 300kbps mi=0.5), FEC')
        phy = self._make_wisun_fan_phy(model, params, phy_name=phy_name)
        return phy
    
    pass